/* MY TRANSFORMATION — APP ENGINE v5 */
const APP_NAME='MY TRANSFORMATION', APP_VERSION='5.0.0';
function appGetProfile(){return storageGetProfile();}
function showSetupScreen(){document.getElementById('setupScreen')?.classList.remove('hidden');document.getElementById('mainApp')?.classList.add('hidden');}
function showMainApplication(){document.getElementById('setupScreen')?.classList.add('hidden');document.getElementById('mainApp')?.classList.remove('hidden');}
function getInputValue(id){return String(document.getElementById(id)?.value??'').trim();}
function saveUserProfile(p){return storageSaveProfile(p);}
function completeSetup(){const old=appGetProfile();const profile={age:getInputValue('setupAge'),sex:getInputValue('setupSex'),height:getInputValue('setupHeight'),weight:getInputValue('setupWeight'),goal:getInputValue('setupGoal'),trainingDays:getInputValue('setupTrainingDays'),trainingDuration:getInputValue('setupTrainingDuration'),trainingPlace:getInputValue('setupTrainingPlace'),meals:getInputValue('setupMeals'),likes:getInputValue('setupLikes'),dislikes:getInputValue('setupDislikes'),allergies:getInputValue('setupAllergies'),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(!validateProfile(profile)){alert('Completa correttamente tutti i campi obbligatori.');return false;}saveUserProfile(profile);refreshNutrition();resetMealsPlan();refreshWorkout();refreshCoach();showMainApplication();updateAllScreens();showScreen('home');return true;}
function editProfile(){const p=appGetProfile();if(!p){showSetupScreen();return;}Object.entries({setupAge:p.age,setupSex:p.sex,setupHeight:p.height,setupWeight:p.weight,setupGoal:p.goal,setupTrainingDays:p.trainingDays,setupTrainingDuration:p.trainingDuration,setupTrainingPlace:p.trainingPlace,setupMeals:p.meals,setupLikes:p.likes||'',setupDislikes:p.dislikes||'',setupAllergies:p.allergies||''}).forEach(([id,v])=>{const e=document.getElementById(id);if(e)e.value=v});showSetupScreen();}
function resetProfile(){if(confirm('Vuoi cancellare profilo e dati?')){storageResetAll();location.reload();}}
function updateDashboard(){const p=appGetProfile(),t=getNutritionTarget(),s=getProgressSummary();if(!p)return;setText('homeWeight',`${p.weight} kg`);setText('homeGoal',{fatloss:'Perdita di grasso',definition:'Definizione',recomp:'Ricomposizione',muscle:'Massa'}[p.goal]||p.goal);setText('homeTraining',p.trainingDays);setText('homeMeals',p.meals);if(t)setText('homeCalories',`${t.calories} kcal`);setText('homeProgressWeight',s.latestWeight!==null?`${s.latestWeight} kg`:'—');setText('homeWorkoutAdherence',`${s.workoutAdherence}%`);setText('homeMealAdherence',`${s.mealAdherence}%`);}
function updateDietScreen(){const t=getNutritionTarget();if(t){setText('dietCalories',t.calories);setText('dietProtein',`${t.protein} g`);setText('dietCarbs',`${t.carbs} g`);setText('dietFat',`${t.fat} g`);}const plan=getSavedMealsPlan(),status=document.getElementById('dietCoachStatus'),section=document.getElementById('dietTodaySection');if(!plan){if(status)status.innerHTML='<span>STATO PIANO</span><strong>Nessuna settimana del Coach importata.</strong><div class="meal-macros">Premi “Genera la mia settimana” per creare il piano.</div>';if(section)section.style.display='none';return;}const day=getMealsDay();if(!day){if(section)section.style.display='none';return;}if(status)status.innerHTML=`<span>STATO PIANO</span><strong>✅ Settimana del Coach attiva</strong><div class="meal-macros">${day.date} · ${day.meals.length} pasti</div>`;if(section)section.style.display='block';setText('dietTodayTitle',day.day);renderMealsPlan(day);}
function renderMealsPlan(day){const ids=['meal1','meal2','meal3','meal4','meal5'];ids.forEach(id=>{const e=document.getElementById(id);if(e)e.innerHTML=''});(day.meals||[]).forEach((meal,index)=>{const e=document.getElementById(`meal${index+1}`);if(!e)return;const foods=(meal.foods||[]).map(f=>`<div class="meal-food"><span>${escapeHTML(f.name)}<small>${f.grams} g</small></span><strong>${f.kcal} kcal</strong></div>`).join('');e.innerHTML=`<div class="meal-header"><strong>${escapeHTML(meal.name)}</strong><span>${meal.totals.kcal} kcal</span></div><div class="meal-foods">${foods}</div><div class="meal-macros">P ${meal.totals.protein} g · C ${meal.totals.carbs} g · G ${meal.totals.fat} g</div><button class="primary-button meal-complete-button" data-meal-id="${escapeHTML(meal.id)}" onclick="completeMeal(this)">${meal.completed?'✅ PASTO COMPLETATO':'SEGNA COME COMPLETATO'}</button>`});setText('dietTotalCalories',`${day.totals.kcal} kcal`);setText('dietTotalProtein',`${day.totals.protein} g`);setText('dietTotalCarbs',`${day.totals.carbs} g`);setText('dietTotalFat',`${day.totals.fat} g`);const next=day.meals.find(m=>!m.completed);if(next)setText('dietNextMeal',`Prossimo: ${next.name}`);else setText('dietNextMeal','✅ Giornata completata');}
function completeMeal(button){const id=button?.dataset?.mealId;if(!id)return false;const result=toggleMealCompleted(id,new Date());if(result===true){button.textContent='✅ PASTO COMPLETATO';button.classList.add('completed');}else{button.textContent='SEGNA COME COMPLETATO';}updateDietScreen();updateDashboard();updateProgressScreen();return result;}
async function importWeeklyCoachDiet(){const r=await importCoachDietFromClipboard();if(!r.success){alert(r.message);return false;}updateAllScreens();showScreen('diet');alert('✅ Settimana alimentare importata correttamente!');return true;}
function updateWorkoutScreen(){const w=getStoredWorkout();if(!w)return;const idx=getTrainingDayIndex(w),today=w.workouts[idx];if(!today)return;setText('workoutTitle',today.name);setText('workoutPhase',`Ciclo mensile: ${today.phase||w.phase}`);setText('workoutExerciseCount',`${today.exercises.length} esercizi`);for(let i=1;i<=10;i++){const e=document.getElementById(`exercise${i}`);if(e)e.innerHTML='';}today.exercises.forEach((x,i)=>{const e=document.getElementById(`exercise${i+1}`);if(!e)return;e.innerHTML=`<div class="exercise-name"><strong>${escapeHTML(x.name)}</strong><small>${escapeHTML(x.muscle)}</small></div><div class="exercise-data">${x.sets} × ${escapeHTML(x.reps)} <span>RIR ${x.rir}</span></div><div class="exercise-rest">Recupero: ${x.rest}s</div><button class="secondary-button" onclick="completeWorkout(${idx},${i})">${x.done?'✅ COMPLETATO':'SEGNA ESERCIZIO'}</button>`});}
function updateProgressScreen(){const s=getProgressSummary();setText('progressWeight',s.latestWeight!==null?`${s.latestWeight} kg`:'—');setText('progressAverage',s.averageWeight7!==null?`${s.averageWeight7} kg`:'—');setText('progressChange',s.weightChange!==null?`${s.weightChange>0?'+':''}${s.weightChange} kg`:'—');setText('progressWorkoutAdherence',`${s.workoutAdherence}%`);setText('progressMealAdherence',`${s.mealAdherence}%`);}
function updateCoachScreen(){const a=generateCoachAnalysis();setText('coachMessage',generateCoachMessage());setText('coachWeightAnalysis',a.weight.message);setText('coachTrainingAnalysis',a.training.message);setText('coachNutritionAnalysis',a.nutrition.message);}
function updateProfileScreen(){const p=appGetProfile();if(!p)return;setText('profileAge',p.age);setText('profileHeight',`${p.height} cm`);setText('profileWeight',`${p.weight} kg`);setText('profileTrainingDays',p.trainingDays);setText('profileMeals',p.meals);}
function updateAllScreens(){updateDashboard();updateDietScreen();updateWorkoutScreen();updateProgressScreen();updateCoachScreen();updateProfileScreen();}
function showScreen(id,button=null){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));const t=document.getElementById(id);if(!t)return;t.classList.add('active');document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));(button||document.querySelector(`.nav button[data-screen="${id}"]`))?.classList.add('active');if(id==='home')updateDashboard();if(id==='diet')updateDietScreen();if(id==='workout')updateWorkoutScreen();if(id==='progress')updateProgressScreen();if(id==='coach')updateCoachScreen();if(id==='profile')updateProfileScreen();window.scrollTo({top:0,behavior:'smooth'});}
function completeWorkout(wi,ei){const ok=completeExercise(wi,ei);updateWorkoutScreen();return ok;}
function recordWeight(weight){const ok=addWeightEntry(weight);if(ok){updateProgressScreen();updateDashboard();updateCoachScreen();}return ok;}
function recordMeasurements(m){return addMeasurementEntry(m);}
function buildCoachWeeklyPrompt(){const p=appGetProfile(),t=getNutritionTarget(),s=getProgressSummary(),meals=Number(p?.meals||3);return `MY TRANSFORMATION — COACH IA\nCrea 7 giorni, esattamente ${meals} pasti/giorno. Usa profilo, target e progressi. Rispetta likes/dislikes/allergie. Varia i pasti. JSON valido בלבד, senza markdown.\nPROFILO:${JSON.stringify(p)}\nTARGET:${JSON.stringify(t)}\nPROGRESSI:${JSON.stringify(s)}\nFormato:\n=== MY_TRANSFORMATION_DIET_START ===\n{"version":"5.0","type":"weekly","week":[{"day":"Lunedì","dayType":"training","meals":[{"name":"Colazione","foods":[{"name":"Alimento","grams":100,"kcal":100,"protein":10,"carbs":10,"fat":5}],"totals":{"kcal":100,"protein":10,"carbs":10,"fat":5}}],"totals":{"kcal":100,"protein":10,"carbs":10,"fat":5}}]}\n=== MY_TRANSFORMATION_DIET_END ===\nControlla: 7 giorni, ${meals} pasti ogni giorno, solo JSON.`;}
async function copyCoachPrompt(){const p=buildCoachWeeklyPrompt();try{await navigator.clipboard.writeText(p);return true;}catch{return false;}}
function openChatGPT(){window.open('https://chatgpt.com/','_blank');}
async function openCoachWeeklyPlan(){if(!appGetProfile()){alert('Prima devi completare il profilo.');showSetupScreen();return false;}if(!(await copyCoachPrompt())){alert('Non riesco a copiare il prompt.');return false;}alert('✅ Prompt copiato. Si aprirà ChatGPT nel browser. Incolla e invia. Poi copia tutta la risposta e torna qui per importarla.');openChatGPT();return true;}
function openChatGPTWithCoachPrompt(mode){return openCoachWeeklyPlan();}
function regenerateDailyMeals(){return importWeeklyCoachDiet();}
function regenerateWorkout(){const w=refreshWorkout();updateWorkoutScreen();return w;}
function setText(id,v){const e=document.getElementById(id);if(e)e.textContent=v??'';}
function escapeHTML(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
function initializeApp(){const p=appGetProfile();if(!p){showSetupScreen();return;}showMainApplication();if(!getNutritionTarget())refreshNutrition();ensureWorkoutCurrentMonth();refreshCoach();updateAllScreens();showScreen('home');}
document.addEventListener('DOMContentLoaded',initializeApp);
window.MY_TRANSFORMATION_APP={openCoachWeeklyPlan,buildCoachWeeklyPrompt,copyCoachPrompt,importWeeklyCoachDiet,regenerateWorkout,updateAllScreens};
