/* MY TRANSFORMATION — MEALS ENGINE v5 — COACH IA ONLY */
const MEALS_SOURCE='coach_ai', MEALS_VERSION='5.0';
function mealsNum(v,f=0){const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:f;}
function mealsRound(v,d=1){const m=10**d;return Math.round(mealsNum(v)*m)/m;}
function mealsProfile(){return storageGetProfile();}
function mondayOfWeek(date=new Date()){const d=new Date(date);d.setHours(0,0,0,0);const day=d.getDay();d.setDate(d.getDate()+(day===0?-6:1-day));return d;}
function dayKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function getImportedDate(i){const d=mondayOfWeek();d.setDate(d.getDate()+i);return dayKey(d);}
function italianDay(i){return ['Lunedì','Martedì','Mercoledì','Giovedì','Venerdì','Sabato','Domenica'][i];}
function cleanCoachResponse(text){let s=String(text||'').trim();const a='=== MY_TRANSFORMATION_DIET_START ===',b='=== MY_TRANSFORMATION_DIET_END ===';const ai=s.indexOf(a),bi=s.indexOf(b);if(ai>=0)s=s.slice(ai+a.length);if(bi>=0){const pos=s.indexOf(b);if(pos>=0)s=s.slice(0,pos);}s=s.replace(/^```(?:json)?\s*/i,'').replace(/```\s*$/,'').trim();return s;}
function extractJson(text){const s=cleanCoachResponse(text), start=s.indexOf('{');if(start<0)throw new Error('Non trovo il JSON della dieta.');let depth=0,inStr=false,esc=false;for(let i=start;i<s.length;i++){const c=s[i];if(esc){esc=false;continue;}if(c==='\\'&&inStr){esc=true;continue;}if(c==='"'){inStr=!inStr;continue;}if(inStr)continue;if(c==='{')depth++;if(c==='}'){depth--;if(depth===0)return s.slice(start,i+1);}}throw new Error('Il JSON della dieta è incompleto.');}
function parseCoachDietText(text){let raw=extractJson(text).replace(/,\s*([}\]])/g,'$1');let data;try{data=JSON.parse(raw);}catch{throw new Error('Il JSON della dieta non è valido.');}const week=Array.isArray(data.week)?data.week:Array.isArray(data.days)?data.days:null;if(!week||week.length!==7)throw new Error('La dieta deve contenere esattamente 7 giorni.');return {...data,week};}
function normalizeFood(f,di,mi,fi){return {id:`meal_${di}_${mi}_${fi}`,name:String(f?.name||f?.food||'Alimento').trim(),grams:mealsRound(mealsNum(f?.grams??f?.g??f?.quantity),0),kcal:mealsRound(mealsNum(f?.kcal??f?.calories),0),protein:mealsRound(mealsNum(f?.protein),1),carbs:mealsRound(mealsNum(f?.carbs??f?.carbohydrates),1),fat:mealsRound(mealsNum(f?.fat),1)};}
function normalizeImportedDiet(data){const p=mealsProfile(),expected=Number(p?.meals)||0;const days=data.week.map((d,di)=>{const ms=Array.isArray(d?.meals)?d.meals:[];if(ms.length!==expected)throw new Error(`Il giorno ${di+1} contiene ${ms.length} pasti invece di ${expected}.`);const meals=ms.map((m,mi)=>{const foods=Array.isArray(m?.foods)?m.foods:[];if(!foods.length)throw new Error(`Il pasto ${mi+1} del giorno ${di+1} non contiene alimenti.`);const nf=foods.map((f,fi)=>normalizeFood(f,di,mi,fi));const totals=nf.reduce((a,x)=>({kcal:a.kcal+x.kcal,protein:a.protein+x.protein,carbs:a.carbs+x.carbs,fat:a.fat+x.fat}),{kcal:0,protein:0,carbs:0,fat:0});return {id:`coach_meal_${di}_${mi}`,name:String(m?.name||`Pasto ${mi+1}`),foods:nf,totals:{kcal:Math.round(totals.kcal),protein:mealsRound(totals.protein,1),carbs:mealsRound(totals.carbs,1),fat:mealsRound(totals.fat,1)},completed:false};});const totals=meals.reduce((a,m)=>({kcal:a.kcal+m.totals.kcal,protein:a.protein+m.totals.protein,carbs:a.carbs+m.totals.carbs,fat:a.fat+m.totals.fat}),{kcal:0,protein:0,carbs:0,fat:0});return {id:`coach_day_${di}`,date:getImportedDate(di),day:italianDay(di),originalDay:String(d?.day||italianDay(di)),dayType:String(d?.dayType||'unknown'),meals,totals:{kcal:Math.round(totals.kcal),protein:mealsRound(totals.protein,1),carbs:mealsRound(totals.carbs,1),fat:mealsRound(totals.fat,1)},target:getNutritionTarget()};});return {version:MEALS_VERSION,type:'weekly',source:MEALS_SOURCE,imported:true,importedAt:new Date().toISOString(),startDate:days[0].date,endDate:days[6].date,days};}
function getSavedMealsPlan(){return storageGetMeals();}
function saveMealsPlan(plan){return plan&&plan.source===MEALS_SOURCE&&plan.imported&&Array.isArray(plan.days)&&plan.days.length===7?storageSaveMeals(plan):false;}
function getMealsDay(date=new Date()){const plan=getSavedMealsPlan();if(!plan) return null;const key=dayKey(date);return plan.days.find(d=>d.date===key)||plan.days[(date.getDay()===0?6:date.getDay()-1)]||null;}
function importCoachDiet(text){try{const plan=normalizeImportedDiet(parseCoachDietText(text));if(!saveMealsPlan(plan))throw new Error('Non è stato possibile salvare la settimana.');return {success:true,plan,message:'Settimana del Coach importata correttamente.'};}catch(e){return {success:false,plan:null,message:e?.message||'Errore durante l’importazione.'};}}
async function importCoachDietFromClipboard(){if(!navigator.clipboard?.readText)return {success:false,message:'Il browser non permette di leggere gli appunti.'};try{const t=await navigator.clipboard.readText();if(!t.trim())return {success:false,message:'Gli appunti sono vuoti.'};return importCoachDiet(t);}catch{return {success:false,message:'Impossibile leggere gli appunti.'};}}
function toggleMealCompleted(mealId,date=new Date()){const plan=getSavedMealsPlan();const day=getMealsDay(date);if(!plan||!day)return false;const meal=day.meals.find(m=>String(m.id)===String(mealId));if(!meal)return false;meal.completed=!meal.completed;meal.completedAt=meal.completed?new Date().toISOString():null;day.completed=day.meals.every(m=>m.completed===true);if(meal.completed)logMealCompletion(meal.name,meal.totals.kcal);return saveMealsPlan(plan)&&meal.completed;}
function getMealCompletionStats(plan=getSavedMealsPlan()){const ms=(plan?.days||[]).flatMap(d=>d.meals||[]);const done=ms.filter(m=>m.completed).length;return {completed:done,total:ms.length,percentage:ms.length?Math.round(done/ms.length*100):0};}
function resetMealsPlan(){return storageDeleteMeals();}
function getMealsStatus(){const p=getSavedMealsPlan();return {exists:!!p,source:p?.source||null,days:p?.days?.length||0,imported:!!p?.imported,waitingForCoach:!p};}
function refreshDailyMeals(date=new Date()){return getMealsDay(date);}
function refreshWeeklyMeals(){return getSavedMealsPlan();}
